### PR TITLE
Add ConnectedSTL class to 3tk for chopping objects

### PR DESCRIPTION
**Pull request by eyal0**
ConnectedSTL stores an STL file along with the edge connectivity information.  This allows for isolating objects inside a single STL and also allows us to split objects along a plane.

This will be used to fix https://github.com/kennethjiang/OctoPrint-Slicer/issues/135 after an interface is added to OctoPrint-Slicer.

### CODE REVIEW

**Comment by kennethjiang** [comment]
@eyal0 thx again for this great PR.

`npm test` works without any problem. However when I do `npm run dev` and open `http://localhost:7000/examples/#analyzers_buffergeometry_split` in browser, I got error:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

This error has to do with `babel-polyfill` package that you added. I spent quite some time to research a solution but couldn't find one.

Any idea how we can get the example pages to work again?

**Comment by eyal0** [comment]
I'll take a look.  It might have to do with something that I did in mocha.opts:

`-r jsdom-global/register --require babel-polyfill --reporter test/istanbul.reporter.js --recursive --compilers js:babel-register`

~I've also found something not working in the new split code.  Don't merge this PR just yet.~ Never mind, just a mistake in my testing.

**Comment by eyal0** [comment]
I fixed the examples with [this commit](https://github.com/kennethjiang/3tk/pull/7/commits/afee0c7c5cf5ec214072a3549511a0d990a82aee).

**Comment by kennethjiang** [comment]
I merged this PR. Thanks again @eyal0 for your awesome work.

When I tested it, I found that the new `isolatedGeometries` function in `BufferGeometryAnalyzer` has slowed down by 50-100%. Do you think you have a way to speed it up at least on par with the original implementation? That function was already the slowest one used in Slicer Plugin, I don't want it to be even slower. 

Also I refactored your code to have consistent naming with the rest of the package. Please pull from master before you push other changes

**Comment by eyal0** [comment]
Do you have a sample STL file that shows the isolatedBufferGeometries being so slow?  The files in npm test seem to be about the same speed and some are even faster!

Until then, I have an idea to try.

**Comment by kennethjiang** [comment]
I just ran the example page to split. Without the recent changes I clocked it at 1.5s. With the changes I clocked it at 2.5s.

Of course if you can build a couple test cases to meaure it more precisely that'll be awesome!

**Comment by eyal0** [comment]
I see the slowness in the example, too.  Okay, I'll work on it.

Also, I stripped out the color support because it's not useful for STL files but I see that the example uses colors.  That's why, after splitting the example, all the shapes are black and hard to see.  I'll try to fix that, too.

**Pull request merged**
